[package]
name = "rust-fearless-concurrency"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [ "deviding-workloads-in-threads","sharing-data-in-threads", "thread-builder-pattern"]
