[package]
name = "rust-fearless-concurrency"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19.0"

[workspace]
members = [ "atomics", "deviding-workloads-in-threads", "mutexes", "rwlocks", "scoped-thread","sharing-data-in-threads", "thread-builder-pattern", "thread-parking"]
